# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-01 11:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aname', models.CharField(max_length=50)),
                ('ads', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=11)),
                ('postcode', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'aname',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30, null=True)),
                ('phone', models.CharField(max_length=11, null=True)),
                ('sex', models.BooleanField(default=0)),
                ('regtime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'userinfo',
            },
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userinfo.UserInfo'),
        ),
    ]
