# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-01 11:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0002_auto_20190701_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(db_column='cart_count')),
            ],
            options={
                'db_table': 'cartinfo',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('desc', models.CharField(max_length=300)),
                ('details', models.CharField(max_length=500)),
                ('commments', models.CharField(max_length=500)),
                ('picture', models.ImageField(default='xm5-80.jpg', upload_to='static/image')),
            ],
            options={
                'db_table': 'goods',
            },
        ),
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'goodstype',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNo', models.CharField(max_length=50)),
                ('orderdetails', models.TextField()),
                ('address', models.CharField(max_length=50)),
                ('adsname', models.CharField(max_length=30)),
                ('adsphone', models.CharField(max_length=20)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('total', models.IntegerField()),
                ('acount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('orderstatus', models.IntegerField(choices=[(0, '未支付'), (1, '已支付'), (2, '取消订单')], default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userinfo.UserInfo')),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userinfo.GoodsType'),
        ),
        migrations.AddField(
            model_name='cartinfo',
            name='good',
            field=models.ForeignKey(db_column='good_id', on_delete=django.db.models.deletion.CASCADE, to='userinfo.Goods'),
        ),
        migrations.AddField(
            model_name='cartinfo',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='userinfo.UserInfo'),
        ),
    ]
