# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-06 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0003_auto_20190701_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='commments',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='goods',
            name='desc',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='goods',
            name='details',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='goods',
            name='picture',
            field=models.ImageField(default='xm5-80.jpg', null=True, upload_to='static/image'),
        ),
    ]
