# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-08 07:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0004_auto_20190706_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='desc',
            new_name='introduce',
        ),
    ]
