# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-08 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0005_auto_20190708_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodstype',
            name='desc',
        ),
        migrations.AddField(
            model_name='goodstype',
            name='introduce',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
