# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-08 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0006_auto_20190708_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodstype',
            name='title',
        ),
        migrations.AddField(
            model_name='goodstype',
            name='category_type',
            field=models.IntegerField(choices=[(1, '小米手机'), (2, '红米'), (3, '平板.笔记本'), (4, '电视'), (5, '盒子.影音'), (6, '路由器'), (7, '智能硬件'), (8, '服务'), (9, '社区')], default=1),
        ),
    ]
