# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-09 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0007_auto_20190708_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartinfo',
            name='is_selected',
            field=models.BooleanField(default=True),
        ),
    ]
